# Generated by Django 2.1.5 on 2019-04-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20190418_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissiongroup',
            options={'verbose_name': '权限组', 'verbose_name_plural': '权限组'},
        ),
        migrations.RenameField(
            model_name='permissiongroup',
            old_name='tiele',
            new_name='title',
        ),
    ]
