# Generated by Django 2.2.1 on 2019-07-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stark', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
